---
  - name: Connecting to uild server
    hosts: kube
    # become: yes
    # become_user: root
    tasks:
      - name: Create a my_app directory, if it does not exist
        ansible.builtin.file:
          path: /home/ubuntu/my_app
          state: directory

      - name: transfering the file from jenkins to build server
        ansible.posix.synchronize:
          src: ./
          dest: /home/ubuntu/my_app

      - name: Run dockerfile on build server
        ansible.builtin.shell: docker build -t {{ job_name }}:{{ version }} .
        args:
          chdir: /home/ubuntu/my_app

      - name: Docker image tagging(Versioning)
        ansible.builtin.shell: docker image tag {{ job_name }}:{{ version }} navaneetkn/{{ job_name }}:{{ version }}
          
      - name: Docker image tagging(latest)
        ansible.builtin.shell: docker image tag {{ job_name }}:{{ version }} navaneetkn/{{ job_name }}:latest
      
      - name: pushing the image to dockerhub
        ansible.builtin.shell: "{{ item }}"
        with_items:
          docker login -u navaneetkn -p {{ password }}
          docker image push navaneetkn/{{ job_name }}:{{ version }}
          docker image push navaneetkn/{{ job_name }}:latest
      

      
      
      
      