---
  - name: Connecting to uild server
    hosts: build_server
    # become: yes
    # become_user: root
    tasks:
      - name: Copy file with owner and permissions
        ansible.builtin.copy:
          src: ./myapp_deployment.yaml
          dest: ./
      
      - name: logging in the docker hub
        ansible.builtin.shell: docker login -u navaneetkn -p {{ password }}

      - name: Deploying the build
        ansible.builtin.shell: kubectl apply -f myapp_deployment.yaml
        args:
          chdir: /home/ubuntu/