apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
      - name: my-app-image
        image: navaneetkn/my_pipeline:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myApp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31200
  type: LoadBalancer